# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77d98f9d85f434928e442dbf3f84cd14a6d2825fecb352396f82e782d3a79c06f2409cb4947bd4ba1848dd1758ddb59f19e1ecae4b09b4775af8b326ab310310

test:
  secret_key_base: dcede4b30b7d5369f603aead30c6fe37b02948da0e895be6ab9986cb32b646617161c93f26581eeb84072bb8490c0590b5e84e5739713fa225549b27596801a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
